# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50)),
                ('card_type', models.SmallIntegerField(choices=[(0, 'Discount'), (1, 'Cumulative')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.Profile')),
            ],
        ),
    ]
