# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set([('company', 'card_code')]),
        ),
    ]
